"""Skill: chinese-novelist

Description: 分章节创作引人入胜的中文小说。支持各种题材（悬疑/言情/奇幻/科幻/
历史等），支持10-50章长篇创作，每章3000-5000字，结尾设置悬念钩子。
Author: PenglongHuang
Version: 1.0.0
Generated by Jelly Skill Installer.
"""

from __future__ import annotations

from agent_shell.skills.base import Skill, SkillResult


class ChineseNovelistSkill(Skill):
    """分章节创作引人入胜的中文小说"""

    name = "chinese-novelist"
    description = (
        "分章节创作引人入胜的中文小说。支持各种题材（悬疑/言情/奇幻/科幻/历史等），"
        "支持10-50章长篇创作，每章3000-5000字，结尾设置悬念钩子。"
    )
    triggers = ["/chinese-novelist", "/chinese-novelist-skill", "/中文小说", "/长篇小说"]

    def on_invoke(self, args: str, full_input: str = "", session=None):
        """激活 skill。"""
        prompt = """# Chinese Novelist: 中文小说创作助手

## 三大黄金法则

1. **展示而非讲述** - 用动作和对话表现，不要直接陈述
2. **冲突驱动剧情** - 每章必须有冲突或转折
3. **悬念承上启下** - 每章结尾必须留下钩子

## 特性说明

- **中断续写**：自动检测未完成项目，从断点继续创作
- **自动校验**：创作完成后自动检查字数和质量，不合格自动修复
- **并行写作**（可选）：支持子Agent并行写作

## 核心流程

### 第0步：初始化与偏好加载

读取用户偏好，检测未完成项目（中断续写），展示个性化欢迎。

### 第一阶段：三层递进式问答

通过递进式问答收集创作需求，确定小说定位与标题：

- **核心定位**（必答）：题材创意、主角设定、核心冲突
- **深度定制与规格**：世界观、视角基调、核心主题、读者定位、章节数量、配置确认
- **标题生成**：AI 基于创意元素生成候选标题，用户选择或自定义

### 第二阶段：规划 + 二次确认

创建项目文件夹（`./chinese-novelist/{timestamp}-{小说名称}/`），生成大纲、
人物档案和写作计划JSON，等待用户确认。

### 第2.5步：写作模式选择

规划确认后，选择写作模式：
- **逐章串行**（`serial`）：主 Agent 自己逐章写，全程无中断
- **子Agent并行**（`subagent-parallel`）：将章节分成批次，派生子 Agent 并行写作
- **Agent Teams**（`agent-teams`）：多 Agent 协作模式

### 第三阶段：疯狂创作（无需用户确认）

> 切记，一旦进入这个阶段，所有过程都禁止向用户确认。用户就是你的读者，
> 你必须把完整的小说创作完成才能与用户报告

根据用户选择的写作模式逐章执行创作流程。每章创作前必须读取 `01-大纲.md`
中对应章节的规划信息，严格按大纲创作。支持中断续写。

### 第四阶段：自动校验与修复（无需用户确认）

全程无需用户介入，自动检查所有章节完成度和字数，不合格章节自动重写（最多3轮）。

## 共享机制

偏好系统、写作计划系统、黄金法则详解、字数检查脚本等跨阶段共享机制。

---

用户的要求：{args}

请按照以上流程开始创作。
"""
        return SkillResult(
            skill_name=self.name,
            description=self.description,
            system_addon=prompt.replace("{args}", args or "见接下来的用户消息"),
            remaining_input=args,
            handled=True,
        )
