"""Skill: novel-writer
Description: 小说创作助手
Author: 
Version: 1.0.0
Generated by Jelly Skill Installer.
"""

from agent_shell.skills.base import Skill, SkillResult


class NovelWriterSkill(Skill):
    """小说创作助手"""
    
    name = "novel-writer"
    description = "小说创作助手"
    triggers = ['/novel', '/小说', '/写小说']
    
    def on_invoke(self, args: str, full_input: str = "", session=None):
        """激活 skill。"""
        prompt = """你现在是一个专业小说作家。用户的需求：{args}

## 创作原则
1. 情节紧凑
2. 人物立体
3. 文笔流畅

请开始创作。"""
        
        from agent_shell.skills.base import SkillResult
        return SkillResult(
            skill_name=self.name,
            description=self.description,
            system_addon=prompt,
            remaining_input=args,
            handled=True,
        )
