"""Skill 安装器：从远程 URL 下载并安装 skill。

Skill 定义格式（Markdown）：
```markdown
---
name: novel-writer
description: 小说创作助手，帮助构思情节、塑造人物、撰写章节
triggers:
  - /novel
  - /小说
  - /写小说
---

# Prompt Template

你现在是一个专业小说作家。用户的需求：{args}

## 创作原则
1. 情节紧凑，有起承转合
2. 人物立体，有动机有成长
3. 文笔流畅，有画面感

请根据用户的要求开始创作。
```
"""

from __future__ import annotations

import re
import textwrap
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import urllib.request
import urllib.error

from agent_shell.skills.base import Skill


# 内置 skills 目录
BUILTINS_DIR = Path(__file__).parent / "builtins"


class SkillDefinition:
    """从 Markdown 解析的 skill 定义。"""

    def __init__(
        self,
        name: str,
        description: str,
        triggers: list[str],
        prompt_template: str,
        author: str = "",
        version: str = "1.0.0",
    ):
        self.name = name
        self.description = description
        self.triggers = triggers
        self.prompt_template = prompt_template
        self.author = author
        self.version = version

    def validate(self) -> None:
        """验证 skill 定义是否合法。"""
        if not self.name or not re.match(r'^[a-zA-Z][a-zA-Z0-9_-]*$', self.name):
            raise ValueError(f"Invalid skill name: {self.name!r} (must be alphanumeric, start with letter)")
        if not self.triggers:
            raise ValueError("At least one trigger is required")
        if not self.prompt_template:
            raise ValueError("prompt_template is required")
        # 检查 trigger 格式
        for t in self.triggers:
            if not t.startswith('/'):
                raise ValueError(f"Trigger must start with '/': {t!r}")


def parse_skill_markdown(content: str) -> SkillDefinition:
    """从 Markdown 内容解析 skill 定义。
    
    支持 YAML front matter 格式。
    """
    # 提取 YAML front matter
    front_matter_match = re.match(r'^---\s*\n(.*?)\n---\s*\n(.*)$', content, re.DOTALL)
    
    if not front_matter_match:
        raise ValueError("Invalid skill format: missing YAML front matter (---...---)")
    
    yaml_content = front_matter_match.group(1)
    prompt_template = front_matter_match.group(2).strip()
    
    # 简单 YAML 解析（不依赖 pyyaml）
    metadata = _parse_simple_yaml(yaml_content)
    
    return SkillDefinition(
        name=metadata.get('name', ''),
        description=metadata.get('description', ''),
        triggers=metadata.get('triggers', []),
        prompt_template=prompt_template,
        author=metadata.get('author', ''),
        version=metadata.get('version', '1.0.0'),
    )


def _parse_simple_yaml(yaml_str: str) -> dict[str, Any]:
    """简单的 YAML 解析器，支持 key: value 和 key: [item1, item2] 格式。"""
    result: dict[str, Any] = {}
    current_key = None
    current_list = []
    
    for line in yaml_str.split('\n'):
        stripped = line.strip()
        if not stripped or stripped.startswith('#'):
            continue
        
        # 列表项
        if stripped.startswith('- '):
            if current_key:
                current_list.append(stripped[2:].strip().strip('"').strip("'"))
            continue
        
        # key: value
        if ':' in stripped:
            # 保存之前的列表
            if current_key and current_list:
                result[current_key] = current_list
                current_list = []
            
            key, _, value = stripped.partition(':')
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            
            if value:
                result[key] = value
                current_key = None
            else:
                # 值在下一行（可能是列表）
                current_key = key
    
    # 保存最后的列表
    if current_key and current_list:
        result[current_key] = current_list
    
    return result


def fetch_skill_from_url(url: str) -> str:
    """从 URL 获取 skill 定义内容。"""
    # 验证 URL
    parsed = urlparse(url)
    if parsed.scheme not in ('http', 'https'):
        raise ValueError(f"Unsupported URL scheme: {parsed.scheme}")
    
    try:
        req = urllib.request.Request(url, headers={
            'User-Agent': 'Jelly-Skill-Installer/1.0'
        })
        with urllib.request.urlopen(req, timeout=30) as response:
            content = response.read().decode('utf-8')
            return content
    except urllib.error.URLError as e:
        raise ValueError(f"Failed to fetch skill from {url}: {e}")


def generate_skill_code(definition: SkillDefinition) -> str:
    """根据 skill 定义生成 Python 代码。"""
    # 转义 prompt_template 中的特殊字符
    escaped_template = definition.prompt_template.replace('\\', '\\\\').replace("'''", "\\'\\'\\'")
    
    code = f'''"""Skill: {definition.name}
Description: {definition.description}
Author: {definition.author}
Version: {definition.version}
Generated by Jelly Skill Installer.
"""

from agent_shell.skills.base import Skill, SkillResult


class {definition.name.title().replace("-", "").replace("_", "")}Skill(Skill):
    """{definition.description}"""
    
    name = "{definition.name}"
    description = "{definition.description}"
    triggers = {definition.triggers!r}
    
    def on_invoke(self, args: str, full_input: str = "", session=None):
        """激活 skill。"""
        prompt = """{escaped_template}"""
        
        from agent_shell.skills.base import SkillResult
        return SkillResult(
            skill_name=self.name,
            description=self.description,
            system_addon=prompt,
            remaining_input=args,
            handled=True,
        )
'''
    return code


def install_skill_from_url(url: str, skill_dir: Path | None = None) -> SkillDefinition:
    """从 URL 安装 skill。
    
    Args:
        url: skill 定义的 URL
        skill_dir: 安装目录，默认使用 builtins/
        
    Returns:
        安装的 SkillDefinition
        
    Raises:
        ValueError: 如果安装失败
    """
    if skill_dir is None:
        skill_dir = BUILTINS_DIR
    
    # 1. 获取 skill 定义
    content = fetch_skill_from_url(url)
    
    # 2. 解析
    definition = parse_skill_markdown(content)
    definition.validate()
    
    # 3. 检查是否已存在
    target_file = skill_dir / f"{definition.name}.py"
    if target_file.exists():
        raise ValueError(f"Skill '{definition.name}' already exists at {target_file}")
    
    # 4. 生成代码
    code = generate_skill_code(definition)
    
    # 5. 写入文件
    skill_dir.mkdir(parents=True, exist_ok=True)
    target_file.write_text(code, encoding='utf-8')
    
    return definition


def install_skill_from_definition(
    name: str,
    description: str,
    triggers: list[str],
    prompt_template: str,
    skill_dir: Path | None = None,
    author: str = "",
) -> SkillDefinition:
    """直接从参数安装 skill（供 LLM 调用）。
    
    Args:
        name: skill 名称
        description: 描述
        triggers: 触发词列表
        prompt_template: 提示模板
        skill_dir: 安装目录
        author: 作者
        
    Returns:
        安装的 SkillDefinition
    """
    if skill_dir is None:
        skill_dir = BUILTINS_DIR
    
    definition = SkillDefinition(
        name=name,
        description=description,
        triggers=triggers,
        prompt_template=prompt_template,
        author=author,
    )
    definition.validate()
    
    # 检查是否已存在
    target_file = skill_dir / f"{name}.py"
    if target_file.exists():
        raise ValueError(f"Skill '{name}' already exists at {target_file}")
    
    # 生成代码并写入
    code = generate_skill_code(definition)
    skill_dir.mkdir(parents=True, exist_ok=True)
    target_file.write_text(code, encoding='utf-8')
    
    return definition


def uninstall_skill(name: str, skill_dir: Path | None = None) -> bool:
    """卸载 skill。
    
    Args:
        name: skill 名称
        skill_dir: skill 目录
        
    Returns:
        是否成功删除
    """
    if skill_dir is None:
        skill_dir = BUILTINS_DIR
    
    target_file = skill_dir / f"{name}.py"
    if target_file.exists():
        target_file.unlink()
        # 清理 pycache
        pycache = skill_dir / "__pycache__"
        if pycache.exists():
            for f in pycache.glob(f"{name}.*"):
                f.unlink()
        return True
    return False
