// Offline browser acceptance. Start preview_fixture.py first; see docs/DEVELOPMENT.md.
const { chromium } = require(process.env.JELLY_PLAYWRIGHT || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const url = process.env.JELLY_PREVIEW_URL || 'http://127.0.0.1:8012';
  const browser = await chromium.launch({ headless: true, ...(process.env.JELLY_CHROME ? { executablePath: process.env.JELLY_CHROME } : {}) });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = [];
  const consoleErrors = [];
  const failedResponses = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => {
    if (message.type() === 'error') {
      const location = message.location();
      consoleErrors.push(`${message.text()} @ ${location.url || 'unknown'}:${location.lineNumber || 0}`);
    }
  });
  page.on('response', response => {
    if (response.status() >= 400) failedResponses.push(`${response.status()} ${response.url()}`);
  });
  fs.mkdirSync('scratch/screenshots', { recursive: true });
  await page.goto(url);
  const projects = (await (await page.request.get(url + '/api/projects')).json()).projects;
  const research = projects.find(p => p.name === '产品探索');
  const sessions = (await (await page.request.get(url + '/api/sessions')).json()).sessions;
  const session = sessions.find(s => s.project_id === research.id);
  const seededSession = page.locator('.session-item').filter({ hasText: session.title }).locator('.session-open');
  await seededSession.focus();
  await seededSession.press('Enter');
  await page.locator('.document-sheet h1').waitFor();
  assert.match(await page.locator('.document-sheet').innerText(), /轻量级项目管理工具/);
  const chatTab = page.getByRole('tab', { name: '对话', exact: true });
  await chatTab.focus();
  await chatTab.press('ArrowRight');
  assert.equal(await page.getByRole('tab', { name: /^执行记录/ }).getAttribute('aria-selected'), 'true');
  await page.getByRole('tab', { name: /^执行记录/ }).press('ArrowLeft');
  assert.equal(await chatTab.getAttribute('aria-selected'), 'true');
  const previewTab = page.getByRole('tab', { name: '预览', exact: true });
  await previewTab.focus();
  await previewTab.press('ArrowRight');
  assert.equal(await page.getByRole('tab', { name: '版本与恢复', exact: true }).getAttribute('aria-selected'), 'true');
  await page.getByRole('tab', { name: '版本与恢复', exact: true }).press('ArrowLeft');
  await page.locator('.task-heading').click();
  await page.screenshot({ path: 'scratch/screenshots/workbench-dark.png', fullPage: true });
  await page.getByRole('button', { name: '切换明暗主题' }).click();
  await page.waitForTimeout(300);
  await page.screenshot({ path: 'scratch/screenshots/workbench-light.png', fullPage: true });
  await page.getByRole('button', { name: '切换明暗主题' }).click();
  await page.getByRole('button', { name: '专注阅读', exact: true }).click();
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.focused-preview').count(), 0);
  await page.getByRole('button', { name: '新建项目', exact: true }).click();
  const projectName = `品牌设计 ${Date.now()}`;
  await page.getByLabel('项目名称', { exact: true }).fill(projectName);
  const designRoot = path.resolve(research.cwd, '../design', String(Date.now()));
  fs.mkdirSync(designRoot, { recursive: true });
  await page.getByLabel('工作目录', { exact: true }).fill(designRoot);
  await page.getByLabel('执行权限', { exact: true }).selectOption('auto');
  await page.getByRole('button', { name: '创建项目', exact: true }).click();
  await page.locator('.workspace-selector').filter({ hasText: projectName }).waitFor();
  assert.equal(await page.locator('.document-sheet').count(), 0);
  await page.getByRole('button', { name: '新建任务' }).click();
  await page.locator('.composer textarea:not([disabled])').fill('整理品牌设计项目的交付方案');
  const submitted = page.waitForResponse(response => response.url().endsWith('/run') && response.request().method() === 'POST');
  await page.getByRole('button', { name: '发送', exact: true }).click();
  assert.equal((await submitted).ok(), true);
  await page.reload();
  await page.locator('.document-sheet h1').waitFor();
  await page.locator('.task-state').filter({ hasText: '已就绪' }).waitFor();
  assert.match(await page.locator('.task-breadcrumb').innerText(), new RegExp(projectName));
  await page.getByRole('tab', { name: /^文件 \d/ }).click();
  await page.locator('.messages .artifact-card').filter({ hasText: '功能清单.csv' }).click();
  await page.locator('.ws-code').filter({ hasText: '优先级' }).waitFor();
  assert.equal(await page.locator('.file-tabs [role="tab"]').count(), 2);
  await page.getByRole('tab', { name: /产品方案.md/ }).click();
  await page.getByRole('tab', { name: '版本与恢复', exact: true }).click();
  await page.getByText('查看修改差异', { exact: true }).first().click();
  assert.ok((await page.locator('.change-diff').first().innerText()).length > 0);
  await page.getByRole('tab', { name: '预览', exact: true }).click();
  await page.locator('.project-list button').filter({ hasText: '产品探索' }).click();
  await page.locator('.session-item').filter({ hasText: session.title }).click();
  await page.locator('.document-sheet h1').waitFor();
  await page.getByRole('tab', { name: '对话', exact: true }).click();
  const providerName = `qa-${Date.now()}`;
  await page.getByRole('button', { name: '模型与 API Key 设置' }).click();
  const settingsDialog = page.getByRole('dialog', { name: '模型与 API Key' });
  await settingsDialog.getByRole('button', { name: '+ 添加提供商', exact: true }).click();
  await settingsDialog.getByLabel('提供商名称').fill(providerName);
  await settingsDialog.getByLabel('新提供商默认模型').fill('qa-model');
  const providerCreated = page.waitForResponse(response => response.url().endsWith('/api/providers') && response.request().method() === 'POST');
  await settingsDialog.getByRole('button', { name: '确认添加', exact: true }).click();
  assert.equal((await providerCreated).ok(), true);
  await settingsDialog.getByText(providerName, { exact: true }).waitFor();
  await page.keyboard.press('Escape');
  assert.equal(await settingsDialog.count(), 0);
  assert.equal((await page.request.delete(`${url}/api/providers/${providerName}`)).ok(), true);
  await page.setViewportSize({ width: 1080, height: 675 });
  await page.screenshot({ path: 'scratch/screenshots/workbench-compact.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'scratch/screenshots/workbench-mobile.png', fullPage: true });
  await page.getByRole('button', { name: '关闭工作台', exact: true }).click();
  await page.waitForTimeout(300);
  await page.screenshot({ path: 'scratch/screenshots/workbench-mobile-chat.png', fullPage: true });
  console.log(await page.locator('.sidebar').evaluate(el => ({ sidebarTransform: getComputedStyle(el).transform, sidebarPosition: getComputedStyle(el).position })));
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  console.log(JSON.stringify({ errors, consoleErrors, failedResponses, project: research.name, title: session.title }));
  assert.deepEqual(errors, []);
  assert.deepEqual(consoleErrors, []);
  assert.deepEqual(failedResponses, []);
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
